steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: '/'
  env:
  - 'NODE_ENV=production'
  - 'CI=true'
  - 'SKIP_PREFLIGHT_CHECK=true'
  - 'NPM_CONFIG_LOGLEVEL=error'
  - 'NPM_CONFIG_PROGRESS=false'
  - 'NPM_CONFIG_SPIN=false'
  - 'NPM_CONFIG_FETCH_RETRIES=5'
  - 'NPM_CONFIG_FETCH_RETRY_FACTOR=2'
  - 'NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=10000'
  - 'NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=60000'
  - 'NPM_CONFIG_REGISTRY=https://registry.npmjs.org'
  - 'NPM_CONFIG_COLOR=false'
  - 'NPM_CONFIG_SAVE_EXACT=true'
  - 'NPM_CONFIG_SHRINKWRAP=false'
  volumes:
  - name: 'npm-cache'
    path: '/root/.npm'
    # Other steps in your pipeline can reuse this volume by using the same name.

# This volume can be used to cache Docker layers, reducing build times.
volumes:
- name: 'gcr-cache'
  path: '/var/lib/docker'
  # Other steps in your pipeline can reuse this volume by using the same name.
  
# Push the app to App Engine using the gcloud app deploy command
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud app deploy --quiet
